db:
  image: 'mysql:5.6'
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=jpress
    - MYSQL_DATABASE=jpress
    - MYSQL_USER=jpress
    - MYSQL_PASSWORD=jpress
  labels:
    aliyun.scale: '1'
  volumes:
    - 'jpress-db:/var/lib/mysql:rw'
jpress:
  image: 'fuhai/jpress:1.0.3'
  restart: always
  environment:
    - TZ=Asia/Shanghai
    - JPRESS_DB_HOST=db
    - JPRESS_DB_PORT=3306
    - JPRESS_DB_NAME=jpress
    - JPRESS_DB_USER=jpress
    - JPRESS_DB_PASSWORD=jpress
  labels:
    aliyun.scale: '1'
    aliyun.routing.port_8080: 'http://jpress'
  depends_on:
    - db
  links:
    - db
  volumes:
    - 'jpress-web:/usr/local/tomcat/webapps/ROOT/attachment:rw'
    - 'jpress-web:/usr/local/tomcat/webapps/ROOT/wp-content:rw'